### ISSUE TITLE
Progressive index update?

### ISSUE THREAD

**Issue by pixobit** [k-samuel/faceted-search#16]
Is it possible to update the index, instead of regenerating the whole index every time?
I couldn't find any examples achieving this, but what I would like to do, is monitor products that were changed, and when the cron task runs, only query the changed products, and update the index for those products.

**Comment by k-samuel** [comment]
At the moment, this functionality is not provided. Only a complete rebuild of the index is possible.

**Comment by k-samuel** [comment]
If such functionality is very much needed, I can implement it in the next version. You need to understand that rebuilding will require a full scan of the index and re-allocation of memory for all attributes where the data has changed. This is a rather expensive operation. The update will be ten times slower than the insert.

**Comment by pixobit** [comment]
Hmmm, it doesn't really solve anything if it's slower. My thinking was if i have 500k+ products, then there wiuld be a more efficient progressive solution to regenerate them. Especially if theres always 1 or 2 products that changes

**Comment by k-samuel** [comment]
Ok, I need a few days to work on that possibility. I can release next week

**Comment by pixobit** [comment]
That sounds great! Thanks for the quick response!

**Comment by k-samuel** [comment]
The functional code is ready and is in the [develop branch](https://github.com/k-samuel/faceted-search/tree/develop). You would help me a lot if you can test it on your data before release. It is especially important to understand that there is no fragmentation and growth of the index file with a large number of changes.

**Comment by pixobit** [comment]
Sure, will give it a try, and let you know
