### ISSUE TITLE
Данные для Индекса

### ISSUE THREAD

**Issue by YakovGulyuta** [k-samuel/faceted-search#19]
Здравствуйте. Хочу проянить один момент. Когда я получаю данные для передачи их в поисковый индекс и у меня есть один и тот же товар но с разными характеристиками. Правильно ли я понимаю что подготовленные данные могут быть с одинаковыми айдишниками? ваш пример из доки выглядит так
$data = [
  ['id'=>6, 'color'=>'black', 'price'=>100, 'sale'=>true, 'size'=>36],
['id'=>7, 'color'=>'red', 'price'=>200, 'sale'=>true, 'size'=>50],
 ];
У товара айдишник один в основной таблице, только набор свойств может быть разный. Корреткно ли я добавляю данные в индекс таким ообразом? То есть у одного товара два разных цвета и можно ли размножать таким образом все характеристики товара
       $data = [
           ['id'=>7, 'color'=>'black', 'price'=>100, 'sale'=>true, 'size'=>36],
           ['id'=>7, 'color'=>'red', 'price'=>100, 'sale'=>true, 'size'=>36],
            ['id'=>9, 'color'=>'green', 'price'=>100, 'sale'=>true, 'size'=>40],
      ];

**Comment by k-samuel** [comment]
Добрый день. В $index->addRecord  нужно подвать уникальные идентификаторы. В вашем случае стоит объединить эти записи и передавать списки значений вида:
```php
$index->addRecord($id,[ 'color'=>[‘black’,’red’], 'price'=>100, 'sale'=>true, 'size'=>[36,37,...,40]])
```
Сами атрибуты могут быть массивом с перечислением возможных вариантов

**Comment by k-samuel** [comment]
Получить начальный список доступных фильтров можно сделав запрос не ограниченный фильтрами:
```php 
$search->aggregate(new AggregationQuery());
```
Пример использования есть тут:
https://github.com/k-samuel/faceted-search/tree/master/examples


Результат который возвращает этот метод:

```php 
[
  'price' => [
      21590 => true,
      25690 => true,
      18790 => true,
  ]
]
```
true  -  говорит о том что у этого значения есть id

Можно сделать запрос с подсчетом количества совпадений:
```php 
$search->aggregate((new AggregationQuery())->countItems());
```
Тогда в ответе будет подсчитано кол-во id с таким значением:

```php 
[
    'price' => [
          21590 => 10,
          25690 => 3,
          18790 => 2,
             …
  ]
]
```
Вернуть false не получится из-за особенностей подхода к пересечению множеств внутри индекса.

**Comment by YakovGulyuta** [comment]
По итогу получается что бы понять какие фильтры выбраны в текущем запросе, нужно будет получить изначальные фильтра и сравнить их с действующими фильтрами которые выбрал пользователь. Так получиться узнать какие фильтра нужно будет дизейблить. Правильно я понял?
Что то типа такого 
        $beginFilters = $search->aggregate($aggsQuery->sort(AggregationSort::SORT_DESC));
        $filters = $search->aggregate($aggsQuery->sort(AggregationSort::SORT_DESC)->filters($filters));

**Comment by k-samuel** [comment]
Обычно логика такая:
При первом показе страницы пользователю получаем полный список доступных фильтров. Далее при изменении выбора на уровне frontend ui (JavaScript) скрываем разницу между началом и результатом.

**Comment by YakovGulyuta** [comment]
Получается можно как с фронта этим заниматься, так и с бэка. Тут уже как договоримся.
