### ISSUE TITLE
How to get count for each filter?

### ISSUE THREAD

**Issue by pixobit** [k-samuel/faceted-search#2]
I'm looking to achieve the result in this post https://stackoverflow.com/questions/35418885/multi-select-faceting-in-mysql-how-to-ignore-any-constraints-on-a-facet

**Comment by k-samuel** [comment]
You can use
`
$filterData = $search->findAcceptableFilters($filters);`
`
But now it return only acceptable filters,
`
=== Size ===   === Color ===    === Brand ===
[Small] (0)    [ ] Red (v)      [ ] Nike (v)
[Medium] (v)   [ ] Blue (v)     [ ] Adidas (v)
[Large] (v)    [x] Black (v)    [ ] Reebok (v)
Not
=== Size ===   === Color ===    === Brand ===
[Small] (0)    [ ] Red (1)      [ ] Nike (1)
[Medium] (1)   [ ] Blue (1)     [ ] Adidas (2)
[Large] (1)    [x] Black (2)    [ ] Reebok (1)
`
I think can update the library to solve your case. If you realy need this.

**Comment by pixobit** [comment]
That's really good actually. But getting the counts would be the final goal.
Unfortunatelly ElasticSearch is not an option, as it needs to be working on a shared hosting...

Great job by the way!

**Comment by k-samuel** [comment]
Already done, give me a few hours to test

**Comment by k-samuel** [comment]
Implemented in 1.2.5 https://github.com/k-samuel/faceted-search/releases/tag/1.2.5
```php
// If you want to get acceptable filters values with items count use findAcceptableFiltersCount
// note that filters is not applied for itself for counting
// values count of a particular field depends only on filters imposed on other fields 
$filterData = $search->findAcceptableFiltersCount($filters);
```

**Comment by pixobit** [comment]
That's awesome! Will play around with it over the weekend

**Comment by pixobit** [comment]
If an item has multiple attributes of the same type, for ex. \["id"=>1,"color"=>\["Black","White"\]\], do they need to be separate entries under the same "id"? or it's possible to directly pass an array?

**Comment by k-samuel** [comment]
Multiple attributes can be set as an array ["id"=>1,"color"=>["Black","White"]]
