### ISSUE TITLE
Вопрос по внедрению дополнительным счетчиков

### ISSUE THREAD

**Issue by Djagannath** [k-samuel/faceted-search#21]
Подскажите как можно внедрить такого рода функционал:
У каждого товара есть дополнительные признаки новинка и поступление.
Стоит задача выводить количество товаров по фиьтрам + количество новинок и поступлений в данном фильтре.

Например 
Категории:
  Чехлы (100) +10 +5 (всего 100 шт +10 новинок + 10 поступлений)
....

Пока смотрю ваш пкет и не могу понять как внедрить. 
Была мысль если бы после фильтрации выводились ИД товаров вместо true по каждому фильтру если использовать countItems(false), то можно было бы посчитать сравнив масивы. Пока не понимаю как заставить фильтровать и при этом выводить ИД товаров вместо количества по каждому фильтру.

**Comment by k-samuel** [comment]
Доброго времени суток. Если "новинка" и "поступление" это отдельные bool аттрибуты их можно посчитать стандартным механизмом.
```php
$query = (new AggregationQuery())->filters($filters)->countItems();
```
И вывести как в [Demo](https://github.com/k-samuel/faceted-search/tree/master/examples)  в скобках около фильтра

**Comment by k-samuel** [comment]
Есть простой но очень неоптимальный вариант для каждого значения поля вызвать запрос $search->query($filters) добавляя к исходным фильтрам фильтр по значению этого поля. Если в индексе не очень много данных может сработать. Альтернативный вариант - переделать поведение [в строке](https://github.com/k-samuel/faceted-search/blob/7cd4e576f9147940b15450e1034afb106af90b20/src/Index/Index.php#L206), тут будет необходимо реализовать свой метод подсчета пересечения данных.

**Comment by Djagannath** [comment]
спасибо, буду пробовать
