### ISSUE TITLE
Is it possible somehow to implement a text filter?

### ISSUE THREAD

**Issue by pixobit** [k-samuel/faceted-search#3]
I understand that this is against the indexing mechanism, but I ran into an issue which I'm trying to resolve. Basically it's possible to search products based on some string (that looks inside the title/description), and the result page takes you to the facet filtering page. However, the search term won't be taken into account by this library, therefore the active filters won't reflect the actual available products.

One way I could get around this is to filter the DB for the products, and then just return a list of the product names, but that wouldn't be efficient enough.

**Comment by k-samuel** [comment]
Yes you can use fulltext search in your DB to get  list of products id for Faceted Search limitation.
Then you can limit faceted serarch results using products id array (second argument):
```php
 $search->find($filters, $productIdArray) 
```
