### ISSUE TITLE
Allow strings as identifier.

### ISSUE THREAD

**Issue by daFish** [k-samuel/faceted-search#31]
Hi there,

would it be possible to allow strings as identifiers as opposed to integers?

**Comment by k-samuel** [comment]
Hello. The current implementation does not imply the possibility of using strings as identifiers; this is due to the facet intersection algorithm. As a workaround - you can use the intermediate stage of binding string identifiers in your system to int

**Comment by daFish** [comment]
Thank you, @k-samuel, for this explanation.
