### ISSUE TITLE
Available filter values according to the specified parameters

### ISSUE THREAD

**Issue by janroz** [k-samuel/faceted-search#32]
Hello,

i would like to ask, is there any method that will return the available ranges for a selected set of parameters? For example, I select the material plastic and I would like the parameter "power" returned to me as min = 20 and max = 150. I would update the slider on the frontend accordingly.

```
$query = (new AggregationQuery())->filters($filters)->countItems()->sort();
$data = $search->aggregate($query);
```

$data returns an array of available values from which min and max values can be constructed, but I wonder if there is another way?

**Comment by k-samuel** [comment]
Hello.
You understood everything correctly, the method returns all available values. 
There is no other method for obtaining such data in the library yet.

**Comment by janroz** [comment]
THank you! Last questions. Individual parameter values can be multiple? For example:

```
$data = [
     ['id' => 7, 'color' => ['black', 'red', 'green'] ],
     ['id' => 9, 'color' => 'green']
];
```

Then the parameter ranges. For example, the working temperature is given as -20°C to 45°C. I haven't figured out a way to deal with it, it would probably work:

```
$data = [
     ['id' => 7, 'temp_min' => -20, 'temp_max' => 45 ]
];
```

I just don't know how to filter such data then. When I want to find records that have a working temperature of -5 to 30? I believe that somehow it works.
This library is absolutely amazing, I am amazed at the speed and simplicity. Thanks a lot.

**Comment by k-samuel** [comment]
Record accept multiple values, yes its ok.
```php
  /**
     * Add record to index
     * @param int $recordId
     * @param array<int|string,array<int,mixed>> $recordValues -  ['fieldName'=>'fieldValue','fieldName2'=>['val1','val2']]
     * @return bool
     */
    public function addRecord(int $recordId, array $recordValues): bool
```
Absolutle normal:
```php
$data = [
     ['id' => 7, 'color' => ['black', 'red', 'green'] ],
     ['id' => 9, 'color' => 'green']
];
```
------
It is not possible to specify a range between different attributes for now. Each attribute has its own facet structure. 
An interesting idea, such a need has never arisen before. You can implement it using own custom filter that implements the FilterInterface; most likely, this will not be an easy task.

It is possible to search for a range within one attribute
```php
 // RangeFilter example for numeric property ranges (min - max)
 $filter = new RangeFilter('size', ['min'=>36, 'max'=>40])
 // OR same 
 $filters = [
   new RangeFilter('price', ['min'=>100,'max'=>200])
 ];
```

**Comment by janroz** [comment]
Maybe it can be done somehow? This could work, probably, quite accurately:

```
$filters[] = new RangeFilter('temp_min', ['min' => -20, 'max' => 0]);
$filters[] = new RangeFilter('temp_max', ['min' => 0, 'max' => 40]);
```

I'll have to take a closer look, haven't had a chance yet.

Thanks for all.
