### ISSUE TITLE
Save index in db

### ISSUE THREAD

**Issue by Djagannath** [k-samuel/faceted-search#4]
Can I save index in db and how?

**Comment by k-samuel** [comment]
You can get index data as an array and transform in into json:
```php
/**
*@var Index $searchIndex
*/
$indexData = $searchIndex->getData();
$indexData = json_encode($indexData); 
```
Save into your database (insert row)
```sql
Insert into myTable (indexDataColumn) Values ({$indexData});
```

**Comment by Djagannath** [comment]
> You can get index data as an array and transform in into json:
> 
> ```
> /**
> *@var Index $searchIndex
> */
> $indexData = $searchIndex->getData();
> $indexData = json_encode($indexData); 
> ```
> 
> Save into your database (insert row)
> 
> ```sql
> Insert into myTable (indexDataColumn) Values ({$indexData});
> ```

thx
