### ISSUE TITLE
RangeFilter не работает

### ISSUE THREAD

**Issue by mavmedved** [k-samuel/faceted-search#6]
Приветствую. Очень хочется заюзать, но не работает RangeFilter.
Пример из readme не находит ничего:
```
<?php
use KSamuel\FacetedSearch\Index\ArrayIndex;
use KSamuel\FacetedSearch\Search;
use KSamuel\FacetedSearch\Indexer\Number\RangeIndexer;
use KSamuel\FacetedSearch\Filter\RangeFilter;

$index = new ArrayIndex();
$rangeIndexer = new RangeIndexer(100);
$index->addIndexer('price', $rangeIndexer);

$index->addRecord(1,['price'=>90]);
$index->addRecord(2,['price'=>100]);
$index->addRecord(3,['price'=>150]);
$index->addRecord(4,['price'=>200]);


$filters = [
  new RangeFilter('price', ['min'=>100,'max'=>200])
];

$search = new Search($index);
$result = $search->find($filters);

```

$result будет пустой массив.

При этом если воспользоваться ValueFilter:
```
$filters = [
    new ValueFilter('price', [100, 200]),
    //new RangeFilter('price', ['min'=>100,'max'=>200])
];
```
то вернется range `[2, 3, 4]` - хотя такой результат должен быть у RangeFilter.

RangeFilter также не работате при использовании первого примера из доки, где генерируется индекс в json:
```
$filters = [
    new ValueFilter('color', ['black']),
    // RangeFilter example for numeric property ranges (min - max)
    new RangeFilter('size', ['min'=>36, 'max'=>40])
];
```

Однако ValueFilter там работает верно, и возвращает не range а только переданные значения, без промежуточных.

**Comment by k-samuel** [comment]
Спасибо, что обратили внимание, видимо что-то не покрыто тестами и поломалось в ходе оптимизаций. Исправлю в ближайшее время.

**Comment by k-samuel** [comment]
Fixed in [v2.1.2](https://github.com/k-samuel/faceted-search/releases/tag/2.1.2)

**Comment by k-samuel** [comment]
На всякий случай уточню как работает RangeIndexer из примера, так как его работа может быть не совсем очевидна.

Задача RangeIndexer - уменьшить количество различных значений, объединяя их в диапазоны. Это позволяет экономить RAM и уменьшать количество проходов по данным индекса. 

RangeIndexer стоит использовать для полей с высокой вариантивностью значений. 

Можно ограничиться RangeFilter в таком случае будет поиск более точных совпадений, но при этом размер индекса увеличится, производительность снизится.
```php
$index = new ArrayIndex();

$rangeIndexer = new RangeIndexer(100); // ! оптимизация значений в диапазоны (не обязательна)
$index->addIndexer('price', $rangeIndexer);

$index->addRecord(1,['price'=>90]);  // превращает значение в 0 
$index->addRecord(2,['price'=>100]); // превращает значение в 100 
$index->addRecord(3,['price'=>150]); // превращает значение в 100 
$index->addRecord(4,['price'=>200]); // превращает значение в 200 
```
