### ISSUE TITLE
TypeError: must be of type ?string, int given

### ISSUE THREAD

**Issue by pixobit** [k-samuel/faceted-search#9]
`KSamuel\FacetedSearch\Index\ArrayIndex::mergeFilters(): Argument #2 ($skipKey) must be of type ?string, int given, called in`

I have some generic attribute filters, which are passed as ID, and becomes interpreted as int for the $skipKey variable.
This used to work, but the ?string type enforcement is throwing an error now.
Is there any way I can continue using IDs as the key?
I think this shouldn't be a limitation if possible... If it's intentional, and this is the way it has to work, then perhaps this should throw an error when adding the data, and not only when reading

**Comment by k-samuel** [comment]
Thanks for your feedback.
Yes, you can use filter names as integer values. It seems that I did not take into account such a feature of user data. I'll try to fix it today.

**Comment by k-samuel** [comment]
Fixed in [2.1.6](https://github.com/k-samuel/faceted-search/releases/tag/2.1.6) Please check that it is now working as expected.

**Comment by pixobit** [comment]
That was quick :)
And yes, that fixes it!
Thank You!
